### ISSUE TITLE
Handling Async bind

### ISSUE THREAD

**Issue by nutshellit** [fsprojects/Chessie#10]
Hi,
First of all great work, it is much appreciated.
One area I have struggled with using ROP is making bind work in an Async call/pipeline. I have kludged an Async bind like this (excuse RopResult instead of Result)
![image](https://cloud.githubusercontent.com/assets/1902678/6502234/80142948-c319-11e4-8b8b-1720f0427f88.png)

Any suggestions on an Async approach using Chessie would be most appreciated.

**Comment by ghost** [comment]
Hi,

I encountered the same problems. I would suggest an overload for the `async` builder that allows to bind the `Result` type. Then the computation continues only on success values. 

Each binding of a `Result` type value will lead to a deeper nesting, so you get something like `Async<Result<Result<...>>` which is a bit ugly, but you can use the `Result` type hassle-free within the `async` workflow and flatten the nesting later on if the failure types are equal.

I would appreciate some feedback on this. And great to see that Railway-oriented programming found its way to Github :+1: 

Cheers,
Kai

``` f#
    let flatten (rr : Result<Result<'a,'b>, 'b>) = trial {
        let! r = rr
        return! r
    }

    [<AutoOpen>]
    module AsyncExtensions =

        [<RequireQualifiedAccess>]
        module Async =

                let map f xa = async {
                    let! x = xa
                    return x |> f 
                }

                let invertResult (r : Result<Async<_>, _> ) = async {
                    match r with
                    | Ok (successAsync, msgs) ->
                        let! success = successAsync
                        return (success, msgs) |> Ok 
                    | Fail msgs -> return msgs |> Fail        
                }

                let mapInvertResult (f : 'a -> Async<'b>) (r : Result<'a, 'c>) =
                    f <!> r |> invertResult

    type Microsoft.FSharp.Control.AsyncBuilder with
        member x.Bind(r : Result<'a, 'c>, f:'a -> Async<'b>) : Async<Result<'b, 'c>> = r |> Async.mapInvertResult f


    let xr : Result<int,string> = 42 |> ok
    let yr : Result<float,string> = 42. |> ok
    let zr : Result<decimal,string> = 42M |> ok

    let test = async {
        let! x = xr
        let! y = yr
        let! z  = zr
        return x,y,z  
    }

    let flattened = test |> Async.map (flatten >> flatten)
```

**Comment by nutshellit** [comment]
Hi kfrie,
Thank you so much for you reply, this works and makes sense. I had a little play around with it.
See code snippet below.
In the case of calling an "Async<Result<'a, 'b>>" function in the async workflow it binds as a "Result<int,string>" to r1 and then binds as int to r2. 
Sweet and elegant and solves my problem.

![image](https://cloud.githubusercontent.com/assets/1902678/6546514/ced45774-c5ad-11e4-9681-c3d72becb7e4.png)

They should include it in the Chessie library.

**Comment by forki** [comment]
Please send a pull request. Thanks

**Comment by tpetricek** [comment]
I think that the correct approach for combining the `attempt` computation builder with `async` is to define a completely new builder `asyncAttempt` that combines aspects of both. This would be quite similar to what `asyncSeq` does (which combines `async` and `seq`). See [this blog post](http://tomasp.net/blog/async-sequences.aspx/). You can also see [this article about computation expressions](http://tomasp.net/academic/papers/computation-zoo/) for more detailed discussion on the design.

I guess you can get quite far just by extending the standard AsyncBuilder, but it will always feel hacky in one way or another. So a specialized computation builder would be better. The [ExtCore](https://github.com/jack-pappas/ExtCore) library has a few nice examples of composed builders.

**Comment by pblasucci** [comment]
For what it's worth, I'm inclined to agree with @tpetricek ... But it'd be pretty cool to have `asyncTrial` as part of Chessie.

**Comment by ghost** [comment]
I created a `asyncTrial` builder with overloads of `Bind` for `Async`, `Result` and the combination of both (`AsyncResult`).

That should prevent the use of nested builders and ending up with weird types like `Result<Async<Result<_,_>>>`

``` f#
    let u = async.Return 1.
    let v : Result<_,string> = 2. |> ok
    let w : Result<_,string> = 3. |> ok

    let sum1 : AsyncResult<float, string> = asyncTrial {
        // bind  Async
        let! u' = u
        // bind Result
        let! v' = v
        let! w' = w
        return u'+ v' + w'
    }

    let x : Result<float,_> = "failed" |> fail

    let sum2 : AsyncResult<float, string> = asyncTrial {
        // bind AsyncResult
        let! sum = sum1
        let! x' = x
        return sum + x'
    }

    // success
    let result1 = sum1 |> Async.ofAsyncResult |> Async.RunSynchronously
    // fail
    let result2 = sum2 |> Async.ofAsyncResult |> Async.RunSynchronously    



```

**Comment by mexx** [comment]
@nutshellit does the new `asyncTrial` builder satisfy your needs?

**Comment by nutshellit** [comment]
I'm using Chessie and asyncTrial in my project to implement ROP and it elegantly solves using ROP with async results.

**Comment by mexx** [comment]
Nice to receive such good feedback.
