### ISSUE TITLE
PassWarnFail.html returns 404 on gh-pages

### ISSUE THREAD

**Issue by pblasucci** [fsprojects/Chessie#16]
Interestingly, it _IS_ in the directory alongside other HTML files. 

Maybe this is a caching/propagation thing?

**Comment by mexx** [comment]
Don't forget, GitHub runs on *Unix, letter casing matters.

Edit: Link currently points to `passwarnfail.html`.
Please consider renaming to same scheme like `a tale of 3 nightclubs` uses.
Something like `pass-warn-fail.html`

**Comment by forki** [comment]
Yep. The link to http://fsprojects.github.io/Chessie/PassWarnFail.html seems to work

**Comment by forki** [comment]
So fixing the file name and/or the link and running "build.cmd ReleaseDocs" should solve it.

**Comment by pblasucci** [comment]
Addressed by PR #18
