### ISSUE TITLE
either = map?

### ISSUE THREAD

**Issue by forki** [fsprojects/Chessie#2]
/cc @mexx @theimowski

**Comment by mexx** [comment]
For my understanding is `lift = map`.
`either` can used to escape the monad.

**Comment by theimowski** [comment]
affirmative, `lift = map`. Most of the module is a copy paste from Scott's implementation

**Comment by forki** [comment]
ok. cool.

**Comment by forki** [comment]
please review eb96be5

**Comment by theimowski** [comment]
you reverted the change?

**Comment by forki** [comment]
Yep. It broke paket
