### ISSUE TITLE
Messages lost on apply

### ISSUE THREAD

**Issue by CumpsD** [fsprojects/Chessie#20]
Currently you have the following:

```
    let inline apply wrappedFunction result = 
        match wrappedFunction, result with
        | Ok(f, msgs1), Ok(x, msgs2) -> Ok(f x, msgs1 @ msgs2)
        | Fail errs, Ok(_, msgs) -> Fail(errs)
        | Ok(_, msgs), Fail errs -> Fail(errs)
        | Fail errs1, Fail errs2 -> Fail(errs1)
```

When looking at Scott his ROP implementation he has:

```
let applyR f result =
    match f,result with
    | Success (f,msgs1), Success (x,msgs2) -> 
        (f x, msgs1@msgs2) |> Success 
    | Failure errs, Success (_,msgs) 
    | Success (_,msgs), Failure errs -> 
        errs @ msgs |> Failure
    | Failure errs1, Failure errs2 -> 
        errs1 @ errs2 |> Failure
```

Could we change it in Chessie to either one of these two:
# Option 1

This is identical to Scott's version

```
    let inline apply wrappedFunction result = 
        match wrappedFunction, result with
        | Ok(f, msgs1), Ok(x, msgs2) -> Ok(f x, msgs1 @ msgs2)
        | Fail errs, Ok(_, msgs)
        | Ok(_, msgs), Fail errs -> Fail(errs @ msgs)
        | Fail errs1, Fail errs2 -> Fail(errs1 @ errs2)
```
# Option 2

On fail, don't take the Ok messages along

```
    let inline apply wrappedFunction result = 
        match wrappedFunction, result with
        | Ok(f, msgs1), Ok(x, msgs2) -> Ok(f x, msgs1 @ msgs2)
        | Fail errs, Ok(_, msgs)
        | Ok(_, msgs), Fail errs -> Fail(errs)
        | Fail errs1, Fail errs2 -> Fail(errs1 @ errs2)
```

**Comment by CumpsD** [comment]
Option 2 feel more logical to me, since you can't tell which message was coming from Ok and which was from Fail, and most use case will display Fails on its own

**Comment by ReedCopsey** [comment]
~~Mixing Ok messages with fail messages seems like it'd make usability of the results much more complicated, as it wouldn't be obvious which messages were due to success and which due to fail, only that they switch part way through.~~

+1 @CumpsD - My thoughts exactly.

**Comment by theimowski** [comment]
IIRC from the sample app, the messages for `Ok` case were responsible to carry information about "events" that happened in the system - I'm not however sure what are the advantages of keeping them the same type as the `Fail` messages

**Comment by CumpsD** [comment]
Seems you share option 2 :) No advantages, but this does:

`Fail errs1, Fail errs2 -> Fail(errs1 @ errs2)`

So you don't lose errs2

**Comment by forki** [comment]
I'm for 2)

**Comment by pblasucci** [comment]
@CumpsD This is totally a bug. Good catch. The multiple failure messages _should_ be getting merged together. As for merging the non-failing messages with the failing messages, I'm inclined to just drop the non-failing ones... but I think it's something that'll get sorted once we finally handle #17.

**Comment by CumpsD** [comment]
Shall I send a PR with the fix?

**Comment by CumpsD** [comment]
There you go :)
