### ISSUE TITLE
Using extensions from VB.net

### ISSUE THREAD

**Issue by kellerd** [fsprojects/Chessie#38]
Forked the repository here: https://github.com/kellerd/Chessie

Tried to get Extensions working in .NET.  

Added a test project for it: 
https://github.com/kellerd/Chessie/tests/Chessie.VisualBasic.Test/Chessie.VisualBasic.Test.vbproj

The easiest fix I found was to add `[<assembly: ExtensionAttribute()>]` to Assembly.fs and include it into the fs project.

Ran into an issue when using FAKE, where it won't let me add an attribute in your genFSAssemblyInfo section without specifying parameters to the attribute.

I added an issue to FAKE in the mean time, maybe it'll get some traction, to add the feature
https://github.com/fsharp/FAKE/issues/1115, before I try to create a PR myself

Original problem:
https://github.com/kellerd/Chessie/tree/master

Potential fix:
https://github.com/kellerd/Chessie/tree/Intermediatefix

Unless someone has come across this before or has more experience with it.

**Comment by mexx** [comment]
Hmm, according to the documentation of the `ExtensionAttribute`, see the [Remarks section](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.extensionattribute%28v=vs.110%29.aspx), it's actually should be automatically done by the compiler.
I don't know whether it's worth an issue on [visualfsharp](https://github.com/Microsoft/visualfsharp).

**Comment by mexx** [comment]
@dsyme can you have a look at this?

**Comment by kellerd** [comment]
Looks like @dsyme has done some looking https://github.com/Microsoft/visualfsharp/issues/101

**Comment by kellerd** [comment]
Have a PR as a work around, guys at FAKE found the option I was missing.
